// app/lib/data.js
// Master data — 51 services × 482 cities × 58 counties

export const SERVICES = [
  // ── Legal Documents (connects to MS360) ──────────────────────────────────
  { id: 'living-trust', slug: 'living-trust', name: 'Living Trust', nameEs: 'Fideicomiso en Vida', category: 'estate', leadPrice: 150, ms360Path: '/trust', attorneyMin: 2000, ms360Price: 599, description: 'Protect your assets and avoid probate court for your family.' },
  { id: 'general-poa', slug: 'general-power-of-attorney', name: 'General Power of Attorney', nameEs: 'Poder Notarial General', category: 'estate', leadPrice: 100, ms360Path: '/poa', attorneyMin: 300, ms360Price: 149, description: 'Authorize someone to act on your behalf for financial and legal matters.' },
  { id: 'limited-poa', slug: 'limited-power-of-attorney', name: 'Limited Power of Attorney', nameEs: 'Poder Notarial Limitado', category: 'estate', leadPrice: 100, ms360Path: '/limited-poa', attorneyMin: 250, ms360Price: 99, description: 'Grant specific authority for a single transaction or time period.' },
  { id: 'simple-will', slug: 'last-will-testament', name: 'Last Will & Testament', nameEs: 'Testamento Simple', category: 'estate', leadPrice: 120, ms360Path: '/simple-will', attorneyMin: 400, ms360Price: 149, description: 'Ensure your wishes are carried out and your loved ones are protected.' },
  { id: 'pour-over-will', slug: 'pour-over-will', name: 'Pour-Over Will', nameEs: 'Testamento Pour-Over', category: 'estate', leadPrice: 100, ms360Path: '/pour-over-will', attorneyMin: 400, ms360Price: 199, description: 'Essential companion to a living trust for assets not yet transferred.' },
  { id: 'hipaa', slug: 'hipaa-authorization', name: 'HIPAA Authorization', nameEs: 'Autorización HIPAA', category: 'healthcare', leadPrice: 75, ms360Path: '/hipaa-authorization', attorneyMin: 200, ms360Price: 99, description: 'Allow a trusted person to access your medical records and make health decisions.' },
  { id: 'cert-trust', slug: 'certification-of-trust', name: 'Certification of Trust', nameEs: 'Certificación de Fideicomiso', category: 'estate', leadPrice: 75, ms360Path: '/certification-of-trust', attorneyMin: 300, ms360Price: 99, description: 'Required by banks and institutions to verify your trust without revealing private details.' },
  { id: 'small-estate', slug: 'small-estate-affidavit', name: 'Small Estate Affidavit', nameEs: 'Declaración Jurada de Sucesión', category: 'probate', leadPrice: 125, ms360Path: '/small-estate-affidavit', attorneyMin: 1500, ms360Price: 149, description: 'Claim a deceased person\'s assets without going through full probate.' },
  { id: 'quitclaim', slug: 'quitclaim-deed', name: 'Quitclaim Deed', nameEs: 'Escritura de Traspaso', category: 'realestate', leadPrice: 150, ms360Path: '/quitclaim-deed', attorneyMin: 500, ms360Price: 199, description: 'Transfer property ownership quickly — add a spouse, gift to family, or update after marriage.' },
  { id: 'guardianship', slug: 'guardianship-designation', name: 'Guardianship Designation', nameEs: 'Designación de Guardián', category: 'family', leadPrice: 100, ms360Path: '/guardianship', attorneyMin: 400, ms360Price: 129, description: 'Name who will care for your minor children if something happens to you.' },
  { id: 'llc', slug: 'llc-formation', name: 'LLC Formation', nameEs: 'Formación de LLC', category: 'business', leadPrice: 150, ms360Path: '/llc', attorneyMin: 1500, ms360Price: 799, description: 'Form a California LLC and protect your personal assets from business liability.' },
  { id: 'scorp', slug: 's-corporation', name: 'S-Corporation Formation', nameEs: 'Formación de S-Corporation', category: 'business', leadPrice: 150, ms360Path: '/s-corp-formation', attorneyMin: 2000, ms360Price: 499, description: 'Incorporate your business and save on self-employment taxes.' },
  { id: 'ccorp', slug: 'c-corporation', name: 'C-Corporation Formation', nameEs: 'Formación de C-Corporation', category: 'business', leadPrice: 150, ms360Path: '/c-corp-formation', attorneyMin: 2500, ms360Price: 599, description: 'The gold standard for startups seeking investment and unlimited shareholders.' },
  { id: 'banking-res', slug: 'banking-resolution', name: 'Banking Resolution', nameEs: 'Resolución Bancaria', category: 'business', leadPrice: 75, ms360Path: '/banking-resolution', attorneyMin: 300, ms360Price: 99, description: 'Required by banks to open a business account for your LLC or corporation.' },
  { id: 'contractor', slug: 'contractor-agreement', name: 'Contractor Agreement', nameEs: 'Contrato de Contratista', category: 'business', leadPrice: 100, ms360Path: '/contractor-agreement', attorneyMin: 500, ms360Price: 149, description: 'Protect your business with a legally solid independent contractor agreement.' },
  { id: 'demand-letter', slug: 'demand-letter', name: 'Demand Letter', nameEs: 'Carta de Demanda', category: 'civil', leadPrice: 100, ms360Path: '/demand-letter', attorneyMin: 400, ms360Price: 99, description: 'Formally request payment or action before filing a lawsuit.' },
  { id: 'bill-of-sale', slug: 'bill-of-sale', name: 'Bill of Sale', nameEs: 'Carta de Venta', category: 'civil', leadPrice: 75, ms360Path: '/bill-of-sale', attorneyMin: 200, ms360Price: 69, description: 'Document a vehicle, equipment, or personal property sale legally.' },
  { id: 'affidavit', slug: 'affidavit', name: 'Affidavit', nameEs: 'Declaración Jurada', category: 'civil', leadPrice: 75, ms360Path: '/affidavit', attorneyMin: 250, ms360Price: 89, description: 'A sworn written statement of facts for use in legal proceedings.' },
  { id: 'revoke-poa', slug: 'revocation-power-of-attorney', name: 'Revocation of Power of Attorney', nameEs: 'Revocación de Poder Notarial', category: 'estate', leadPrice: 75, ms360Path: '/revocation-poa', attorneyMin: 200, ms360Price: 59, description: 'Formally cancel an existing power of attorney.' },
  { id: 'auth-letter', slug: 'authorization-letter', name: 'Authorization Letter', nameEs: 'Carta de Autorización', category: 'civil', leadPrice: 75, ms360Path: '/authorization-letter', attorneyMin: 150, ms360Price: 49, description: 'Authorize another person to act on your behalf for a specific purpose.' },
  { id: 'promissory', slug: 'promissory-note', name: 'Promissory Note', nameEs: 'Pagaré', category: 'civil', leadPrice: 75, ms360Path: '/promissory-note', attorneyMin: 300, ms360Price: 89, description: 'A legally binding promise to repay a loan with specific terms.' },
  { id: 'travel-auth', slug: 'travel-authorization', name: 'Child Travel Authorization', nameEs: 'Autorización de Viaje', category: 'family', leadPrice: 75, ms360Path: '/travel-authorization', attorneyMin: 200, ms360Price: 49, description: 'Allow your child to travel internationally with another adult.' },
  { id: 'apostille', slug: 'apostille-letter', name: 'Apostille Letter', nameEs: 'Carta de Apostilla', category: 'civil', leadPrice: 75, ms360Path: '/apostille-letter', attorneyMin: 300, ms360Price: 79, description: 'Authenticate documents for use in foreign countries.' },
  { id: 'corp-minutes', slug: 'corporate-minutes', name: 'Corporate Minutes', nameEs: 'Actas Corporativas', category: 'business', leadPrice: 75, ms360Path: '/corporate-minutes', attorneyMin: 400, ms360Price: 149, description: 'Required annual meeting minutes to keep your corporation in good standing.' },
  { id: 'lease-review', slug: 'lease-agreement-review', name: 'Lease Agreement', nameEs: 'Revisión de Contrato de Arrendamiento', category: 'realestate', leadPrice: 125, ms360Path: null, attorneyMin: 500, ms360Price: null, description: 'Get a lease agreement reviewed or drafted by a California attorney.' },

  // ── Immigration ─────────────────────────────────────────────────────────
  { id: 'green-card', slug: 'green-card-application', name: 'Green Card Application', nameEs: 'Solicitud de Tarjeta Verde', category: 'immigration', leadPrice: 200, ms360Path: null, attorneyMin: 3000, ms360Price: null, description: 'Permanent residency in the United States — family, employment, or diversity paths.' },
  { id: 'citizenship', slug: 'us-citizenship-naturalization', name: 'US Citizenship / Naturalization', nameEs: 'Ciudadanía Americana', category: 'immigration', leadPrice: 175, ms360Path: null, attorneyMin: 2500, ms360Price: null, description: 'Become a US citizen through the naturalization process (N-400).' },
  { id: 'daca', slug: 'daca-renewal', name: 'DACA Renewal', nameEs: 'Renovación de DACA', category: 'immigration', leadPrice: 150, ms360Path: null, attorneyMin: 1500, ms360Price: null, description: 'Renew your Deferred Action for Childhood Arrivals status before it expires.' },
  { id: 'work-visa', slug: 'work-visa', name: 'Work Visa', nameEs: 'Visa de Trabajo', category: 'immigration', leadPrice: 175, ms360Path: null, attorneyMin: 3500, ms360Price: null, description: 'H-1B, L-1, O-1, and other employment-based visas for California workers.' },
  { id: 'family-petition', slug: 'family-petition', name: 'Family Petition', nameEs: 'Petición Familiar', category: 'immigration', leadPrice: 175, ms360Path: null, attorneyMin: 2500, ms360Price: null, description: 'Bring your family to the US through the family-based immigration process (I-130).' },
  { id: 'asylum', slug: 'asylum-application', name: 'Asylum Application', nameEs: 'Solicitud de Asilo', category: 'immigration', leadPrice: 200, ms360Path: null, attorneyMin: 5000, ms360Price: null, description: 'Seek protection in the United States based on persecution in your home country.' },
  { id: 'removal-defense', slug: 'removal-defense', name: 'Removal Defense / Deportation', nameEs: 'Defensa de Deportación', category: 'immigration', leadPrice: 250, ms360Path: null, attorneyMin: 5000, ms360Price: null, description: 'Fight deportation and protect your right to remain in the United States.' },
  { id: 'tps', slug: 'temporary-protected-status', name: 'Temporary Protected Status (TPS)', nameEs: 'Estatus de Protección Temporal', category: 'immigration', leadPrice: 150, ms360Path: null, attorneyMin: 1500, ms360Price: null, description: 'Apply for or renew TPS if your country has been designated by the US government.' },
  { id: 'uscis-appeal', slug: 'uscis-appeal', name: 'USCIS Appeal / Denial', nameEs: 'Apelación USCIS', category: 'immigration', leadPrice: 200, ms360Path: null, attorneyMin: 3000, ms360Price: null, description: 'Appeal a denied immigration application or petition.' },
  { id: 'consular', slug: 'consular-processing', name: 'Consular Processing', nameEs: 'Procesamiento Consular', category: 'immigration', leadPrice: 175, ms360Path: null, attorneyMin: 3000, ms360Price: null, description: 'Obtain an immigrant visa at a US consulate in your home country.' },

  // ── Personal Injury / Accidents ─────────────────────────────────────────
  { id: 'car-accident', slug: 'car-accident-attorney', name: 'Car Accident Attorney', nameEs: 'Abogado de Accidente de Auto', category: 'injury', leadPrice: 400, ms360Path: null, attorneyMin: null, ms360Price: null, description: 'Get the maximum compensation for your car accident injuries and damages.' },
  { id: 'truck-accident', slug: 'truck-accident-attorney', name: 'Truck Accident Attorney', nameEs: 'Abogado de Accidente de Camión', category: 'injury', leadPrice: 500, ms360Path: null, attorneyMin: null, ms360Price: null, description: 'Truck accidents cause catastrophic injuries — you need an experienced attorney.' },
  { id: 'slip-fall', slug: 'slip-and-fall-attorney', name: 'Slip and Fall Attorney', nameEs: 'Abogado de Caída', category: 'injury', leadPrice: 300, ms360Path: null, attorneyMin: null, ms360Price: null, description: 'Premises liability — hold property owners accountable for unsafe conditions.' },
  { id: 'workers-comp', slug: 'workers-compensation', name: "Workers' Compensation", nameEs: 'Compensación Laboral', category: 'injury', leadPrice: 300, ms360Path: null, attorneyMin: null, ms360Price: null, description: 'Injured on the job? Get the benefits you deserve from your employer.' },
  { id: 'wrongful-death', slug: 'wrongful-death-attorney', name: 'Wrongful Death Attorney', nameEs: 'Muerte por Negligencia', category: 'injury', leadPrice: 500, ms360Path: null, attorneyMin: null, ms360Price: null, description: 'Pursue justice and financial compensation after losing a loved one due to negligence.' },
  { id: 'dog-bite', slug: 'dog-bite-attorney', name: 'Dog Bite Attorney', nameEs: 'Abogado de Mordida de Perro', category: 'injury', leadPrice: 250, ms360Path: null, attorneyMin: null, ms360Price: null, description: 'California has strict liability for dog bites — get full compensation for your injuries.' },
  { id: 'rideshare', slug: 'uber-lyft-accident-attorney', name: 'Uber / Lyft Accident Attorney', nameEs: 'Abogado de Accidente Uber/Lyft', category: 'injury', leadPrice: 400, ms360Path: null, attorneyMin: null, ms360Price: null, description: 'Rideshare accidents involve complex insurance — let an expert handle it for you.' },
  { id: 'med-mal', slug: 'medical-malpractice', name: 'Medical Malpractice', nameEs: 'Negligencia Médica', category: 'injury', leadPrice: 500, ms360Path: null, attorneyMin: null, ms360Price: null, description: 'Harmed by a doctor, hospital, or healthcare provider? You may have a case.' },

  // ── Family Law ───────────────────────────────────────────────────────────
  { id: 'divorce', slug: 'divorce-attorney', name: 'Divorce Attorney', nameEs: 'Abogado de Divorcio', category: 'family', leadPrice: 150, ms360Path: null, attorneyMin: 5000, ms360Price: null, description: 'Navigate divorce proceedings in California with experienced legal representation.' },
  { id: 'child-custody', slug: 'child-custody-attorney', name: 'Child Custody Attorney', nameEs: 'Abogado de Custodia', category: 'family', leadPrice: 150, ms360Path: null, attorneyMin: 4000, ms360Price: null, description: 'Protect your parental rights and your children\'s best interests.' },
  { id: 'child-support', slug: 'child-support', name: 'Child Support', nameEs: 'Manutención de Hijos', category: 'family', leadPrice: 125, ms360Path: null, attorneyMin: 2500, ms360Price: null, description: 'Establish, modify, or enforce child support orders in California.' },
  { id: 'adoption', slug: 'adoption-attorney', name: 'Adoption Attorney', nameEs: 'Abogado de Adopción', category: 'family', leadPrice: 150, ms360Path: null, attorneyMin: 5000, ms360Price: null, description: 'Complete your family through stepparent, independent, or agency adoption.' },
  { id: 'restraining-order', slug: 'restraining-order', name: 'Restraining Order', nameEs: 'Orden de Restricción', category: 'family', leadPrice: 125, ms360Path: null, attorneyMin: 2000, ms360Price: null, description: 'Get immediate legal protection from domestic violence or harassment.' },

  // ── Real Estate ──────────────────────────────────────────────────────────
  { id: 'home-purchase', slug: 'real-estate-attorney', name: 'Real Estate Attorney', nameEs: 'Abogado de Bienes Raíces', category: 'realestate', leadPrice: 175, ms360Path: null, attorneyMin: 2000, ms360Price: null, description: 'Legal guidance for buying, selling, or disputing real property in California.' },
  { id: 'landlord-tenant', slug: 'landlord-tenant-attorney', name: 'Landlord-Tenant Attorney', nameEs: 'Abogado de Arrendador-Arrendatario', category: 'realestate', leadPrice: 150, ms360Path: null, attorneyMin: 2500, ms360Price: null, description: 'Evictions, habitability disputes, security deposits — get expert help.' },
  { id: 'foreclosure', slug: 'foreclosure-defense', name: 'Foreclosure Defense', nameEs: 'Defensa de Ejecución Hipotecaria', category: 'realestate', leadPrice: 200, ms360Path: null, attorneyMin: 3000, ms360Price: null, description: 'Fight foreclosure and explore loan modification, short sale, or bankruptcy options.' },
];

export const CATEGORIES = {
  estate:      { name: 'Estate Planning', color: '#1E3A8A', icon: '🏛️' },
  business:    { name: 'Business Law',    color: '#065F46', icon: '💼' },
  immigration: { name: 'Immigration Law', color: '#7C3AED', icon: '🌎' },
  injury:      { name: 'Personal Injury', color: '#B91C1C', icon: '⚖️' },
  family:      { name: 'Family Law',      color: '#B45309', icon: '👨‍👩‍👧' },
  realestate:  { name: 'Real Estate',     color: '#0E7490', icon: '🏠' },
  probate:     { name: 'Probate',         color: '#374151', icon: '📋' },
  healthcare:  { name: 'Healthcare',      color: '#065F46', icon: '🏥' },
  civil:       { name: 'Civil Law',       color: '#374151', icon: '📄' },
};

// 482 California cities with county, population, and lat/lng for local context
export const CA_CITIES = [
  { city: 'Los Angeles', slug: 'los-angeles', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 3898747, lat: 34.0522, lng: -118.2437, courthouse: 'Stanley Mosk Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'San Diego', slug: 'san-diego', county: 'San Diego', countySlug: 'san-diego-county', pop: 1386932, lat: 32.7157, lng: -117.1611, courthouse: 'San Diego Superior Court', recorder: 'San Diego County Assessor/Recorder' },
  { city: 'San Jose', slug: 'san-jose', county: 'Santa Clara', countySlug: 'santa-clara-county', pop: 1013240, lat: 37.3382, lng: -121.8863, courthouse: 'Santa Clara Superior Court', recorder: 'Santa Clara County Clerk-Recorder' },
  { city: 'San Francisco', slug: 'san-francisco', county: 'San Francisco', countySlug: 'san-francisco-county', pop: 874784, lat: 37.7749, lng: -122.4194, courthouse: 'San Francisco Superior Court', recorder: 'SF County Assessor-Recorder' },
  { city: 'Fresno', slug: 'fresno', county: 'Fresno', countySlug: 'fresno-county', pop: 542107, lat: 36.7378, lng: -119.7871, courthouse: 'Fresno Superior Court', recorder: 'Fresno County Clerk-Recorder' },
  { city: 'Sacramento', slug: 'sacramento', county: 'Sacramento', countySlug: 'sacramento-county', pop: 524943, lat: 38.5816, lng: -121.4944, courthouse: 'Sacramento Superior Court', recorder: 'Sacramento County Clerk-Recorder' },
  { city: 'Long Beach', slug: 'long-beach', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 466742, lat: 33.7701, lng: -118.1937, courthouse: 'Long Beach Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Oakland', slug: 'oakland', county: 'Alameda', countySlug: 'alameda-county', pop: 440646, lat: 37.8044, lng: -122.2712, courthouse: 'Rene C. Davidson Courthouse', recorder: 'Alameda County Clerk-Recorder' },
  { city: 'Bakersfield', slug: 'bakersfield', county: 'Kern', countySlug: 'kern-county', pop: 407000, lat: 35.3733, lng: -119.0187, courthouse: 'Kern County Superior Court', recorder: 'Kern County Clerk-Recorder' },
  { city: 'Anaheim', slug: 'anaheim', county: 'Orange', countySlug: 'orange-county', pop: 346824, lat: 33.8353, lng: -117.9145, courthouse: 'West Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'Santa Ana', slug: 'santa-ana', county: 'Orange', countySlug: 'orange-county', pop: 310227, lat: 33.7455, lng: -117.8677, courthouse: 'Central Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'Riverside', slug: 'riverside', county: 'Riverside', countySlug: 'riverside-county', pop: 314998, lat: 33.9806, lng: -117.3755, courthouse: 'Riverside Superior Court', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Stockton', slug: 'stockton', county: 'San Joaquin', countySlug: 'san-joaquin-county', pop: 320804, lat: 37.9577, lng: -121.2908, courthouse: 'San Joaquin Superior Court', recorder: 'San Joaquin County Clerk-Recorder' },
  { city: 'Chula Vista', slug: 'chula-vista', county: 'San Diego', countySlug: 'san-diego-county', pop: 275487, lat: 32.6401, lng: -117.0842, courthouse: 'South Bay Regional Center', recorder: 'San Diego County Assessor/Recorder' },
  { city: 'Irvine', slug: 'irvine', county: 'Orange', countySlug: 'orange-county', pop: 307670, lat: 33.6846, lng: -117.8265, courthouse: 'Lamoreaux Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'Fremont', slug: 'fremont', county: 'Alameda', countySlug: 'alameda-county', pop: 230504, lat: 37.5485, lng: -121.9886, courthouse: 'Fremont Hall of Justice', recorder: 'Alameda County Clerk-Recorder' },
  { city: 'San Bernardino', slug: 'san-bernardino', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 222101, lat: 34.1083, lng: -117.2898, courthouse: 'San Bernardino Justice Center', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Modesto', slug: 'modesto', county: 'Stanislaus', countySlug: 'stanislaus-county', pop: 218464, lat: 37.6391, lng: -120.9969, courthouse: 'Stanislaus Superior Court', recorder: 'Stanislaus County Clerk-Recorder' },
  { city: 'Fontana', slug: 'fontana', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 214547, lat: 34.0922, lng: -117.4350, courthouse: 'Fontana Courthouse', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Oxnard', slug: 'oxnard', county: 'Ventura', countySlug: 'ventura-county', pop: 202063, lat: 34.1975, lng: -119.1771, courthouse: 'Ventura Superior Court', recorder: 'Ventura County Clerk-Recorder' },
  { city: 'Moreno Valley', slug: 'moreno-valley', county: 'Riverside', countySlug: 'riverside-county', pop: 208634, lat: 33.9425, lng: -117.2297, courthouse: 'Hemet Courthouse', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Glendale', slug: 'glendale', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 196543, lat: 34.1425, lng: -118.2551, courthouse: 'Burbank Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Huntington Beach', slug: 'huntington-beach', county: 'Orange', countySlug: 'orange-county', pop: 198711, lat: 33.6595, lng: -117.9988, courthouse: 'Harbor Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'Santa Clarita', slug: 'santa-clarita', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 228673, lat: 34.3917, lng: -118.5426, courthouse: 'San Fernando Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Garden Grove', slug: 'garden-grove', county: 'Orange', countySlug: 'orange-county', pop: 171949, lat: 33.7743, lng: -117.9378, courthouse: 'West Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'Oceanside', slug: 'oceanside', county: 'San Diego', countySlug: 'san-diego-county', pop: 175691, lat: 33.1959, lng: -117.3795, courthouse: 'North County Regional Center', recorder: 'San Diego County Assessor/Recorder' },
  { city: 'Rancho Cucamonga', slug: 'rancho-cucamonga', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 177603, lat: 34.1064, lng: -117.5931, courthouse: 'Rancho Cucamonga Courthouse', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Santa Rosa', slug: 'santa-rosa', county: 'Sonoma', countySlug: 'sonoma-county', pop: 178127, lat: 38.4404, lng: -122.7141, courthouse: 'Sonoma Superior Court', recorder: 'Sonoma County Clerk-Recorder-Assessor' },
  { city: 'Ontario', slug: 'ontario', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 175265, lat: 34.0633, lng: -117.6509, courthouse: 'Ontario Courthouse', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Elk Grove', slug: 'elk-grove', county: 'Sacramento', countySlug: 'sacramento-county', pop: 176124, lat: 38.4088, lng: -121.3716, courthouse: 'Sacramento Superior Court', recorder: 'Sacramento County Clerk-Recorder' },
  { city: 'Corona', slug: 'corona', county: 'Riverside', countySlug: 'riverside-county', pop: 157136, lat: 33.8753, lng: -117.5664, courthouse: 'Corona Courthouse', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Palmdale', slug: 'palmdale', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 169450, lat: 34.5794, lng: -118.1165, courthouse: 'Antelope Valley Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Lancaster', slug: 'lancaster', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 173516, lat: 34.6868, lng: -118.1542, courthouse: 'Antelope Valley Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Salinas', slug: 'salinas', county: 'Monterey', countySlug: 'monterey-county', pop: 163542, lat: 36.6777, lng: -121.6555, courthouse: 'Monterey Superior Court', recorder: 'Monterey County Clerk-Recorder' },
  { city: 'Pomona', slug: 'pomona', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 151348, lat: 34.0552, lng: -117.7522, courthouse: 'Pomona Courthouse South', recorder: 'LA County Registrar-Recorder' },
  { city: 'Escondido', slug: 'escondido', county: 'San Diego', countySlug: 'san-diego-county', pop: 151038, lat: 33.1192, lng: -117.0864, courthouse: 'North County Regional Center', recorder: 'San Diego County Assessor/Recorder' },
  { city: 'Torrance', slug: 'torrance', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 147067, lat: 33.8358, lng: -118.3406, courthouse: 'Torrance Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Sunnyvale', slug: 'sunnyvale', county: 'Santa Clara', countySlug: 'santa-clara-county', pop: 155805, lat: 37.3688, lng: -122.0363, courthouse: 'Santa Clara Superior Court', recorder: 'Santa Clara County Clerk-Recorder' },
  { city: 'Hayward', slug: 'hayward', county: 'Alameda', countySlug: 'alameda-county', pop: 162954, lat: 37.6688, lng: -122.0808, courthouse: 'Hayward Hall of Justice', recorder: 'Alameda County Clerk-Recorder' },
  { city: 'Pasadena', slug: 'pasadena', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 138699, lat: 34.1478, lng: -118.1445, courthouse: 'Pasadena Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Fullerton', slug: 'fullerton', county: 'Orange', countySlug: 'orange-county', pop: 143617, lat: 33.8704, lng: -117.9242, courthouse: 'North Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'Roseville', slug: 'roseville', county: 'Placer', countySlug: 'placer-county', pop: 147773, lat: 38.7521, lng: -121.2880, courthouse: 'Placer Superior Court', recorder: 'Placer County Clerk-Recorder' },
  { city: 'Visalia', slug: 'visalia', county: 'Tulare', countySlug: 'tulare-county', pop: 141384, lat: 36.3302, lng: -119.2921, courthouse: 'Tulare Superior Court', recorder: 'Tulare County Clerk-Recorder' },
  { city: 'Concord', slug: 'concord', county: 'Contra Costa', countySlug: 'contra-costa-county', pop: 129295, lat: 37.9780, lng: -122.0311, courthouse: 'Contra Costa Superior Court', recorder: 'Contra Costa County Clerk-Recorder' },
  { city: 'Thousand Oaks', slug: 'thousand-oaks', county: 'Ventura', countySlug: 'ventura-county', pop: 126683, lat: 34.1706, lng: -118.8376, courthouse: 'Ventura Superior Court', recorder: 'Ventura County Clerk-Recorder' },
  { city: 'Victorville', slug: 'victorville', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 134810, lat: 34.5362, lng: -117.2928, courthouse: 'Victorville Courthouse', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Simi Valley', slug: 'simi-valley', county: 'Ventura', countySlug: 'ventura-county', pop: 124237, lat: 34.2694, lng: -118.7815, courthouse: 'Ventura Superior Court', recorder: 'Ventura County Clerk-Recorder' },
  { city: 'Berkeley', slug: 'berkeley', county: 'Alameda', countySlug: 'alameda-county', pop: 124321, lat: 37.8715, lng: -122.2730, courthouse: 'René C. Davidson Courthouse', recorder: 'Alameda County Clerk-Recorder' },
  { city: 'Santa Clara', slug: 'santa-clara', county: 'Santa Clara', countySlug: 'santa-clara-county', pop: 127647, lat: 37.3541, lng: -121.9552, courthouse: 'Santa Clara Superior Court', recorder: 'Santa Clara County Clerk-Recorder' },
  { city: 'El Monte', slug: 'el-monte', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 106587, lat: 34.0686, lng: -118.0276, courthouse: 'El Monte Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Inglewood', slug: 'inglewood', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 109673, lat: 33.9617, lng: -118.3531, courthouse: 'Inglewood Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Vallejo', slug: 'vallejo', county: 'Solano', countySlug: 'solano-county', pop: 121275, lat: 38.1041, lng: -122.2566, courthouse: 'Solano Superior Court', recorder: 'Solano County Clerk-Recorder' },
  { city: 'Downey', slug: 'downey', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 111786, lat: 33.9401, lng: -118.1332, courthouse: 'Downey Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Costa Mesa', slug: 'costa-mesa', county: 'Orange', countySlug: 'orange-county', pop: 111918, lat: 33.6411, lng: -117.9187, courthouse: 'Harbor Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'Clovis', slug: 'clovis', county: 'Fresno', countySlug: 'fresno-county', pop: 120124, lat: 36.8252, lng: -119.7029, courthouse: 'Fresno Superior Court', recorder: 'Fresno County Clerk-Recorder' },
  { city: 'West Covina', slug: 'west-covina', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 107740, lat: 34.0686, lng: -117.9390, courthouse: 'West Covina Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Norwalk', slug: 'norwalk', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 103949, lat: 33.9022, lng: -118.0817, courthouse: 'Norwalk Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Burbank', slug: 'burbank', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 103340, lat: 34.1808, lng: -118.3090, courthouse: 'Burbank Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Antioch', slug: 'antioch', county: 'Contra Costa', countySlug: 'contra-costa-county', pop: 113982, lat: 37.9966, lng: -121.7080, courthouse: 'Pittsburg Courthouse', recorder: 'Contra Costa County Clerk-Recorder' },
  { city: 'Richmond', slug: 'richmond', county: 'Contra Costa', countySlug: 'contra-costa-county', pop: 114070, lat: 37.9358, lng: -122.3478, courthouse: 'Richmond Courthouse', recorder: 'Contra Costa County Clerk-Recorder' },
  { city: 'Murrieta', slug: 'murrieta', county: 'Riverside', countySlug: 'riverside-county', pop: 116800, lat: 33.5539, lng: -117.2139, courthouse: 'Southwest Justice Center', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Temecula', slug: 'temecula', county: 'Riverside', countySlug: 'riverside-county', pop: 114761, lat: 33.4936, lng: -117.1484, courthouse: 'Southwest Justice Center', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Santa Maria', slug: 'santa-maria', county: 'Santa Barbara', countySlug: 'santa-barbara-county', pop: 109026, lat: 34.9530, lng: -120.4357, courthouse: 'Santa Barbara Superior Court North', recorder: 'Santa Barbara County Clerk-Recorder' },
  { city: 'Jurupa Valley', slug: 'jurupa-valley', county: 'Riverside', countySlug: 'riverside-county', pop: 106993, lat: 33.9975, lng: -117.4855, courthouse: 'Riverside Superior Court', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'El Cajon', slug: 'el-cajon', county: 'San Diego', countySlug: 'san-diego-county', pop: 103092, lat: 32.7948, lng: -116.9625, courthouse: 'El Cajon Courthouse', recorder: 'San Diego County Assessor/Recorder' },
  { city: 'Compton', slug: 'compton', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 97559, lat: 33.8958, lng: -118.2201, courthouse: 'Compton Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Rialto', slug: 'rialto', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 103526, lat: 34.1064, lng: -117.3703, courthouse: 'San Bernardino Justice Center', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Daly City', slug: 'daly-city', county: 'San Mateo', countySlug: 'san-mateo-county', pop: 104901, lat: 37.6879, lng: -122.4702, courthouse: 'Hall of Justice & Records', recorder: 'San Mateo County Clerk-Recorder' },
  { city: 'Fairfield', slug: 'fairfield', county: 'Solano', countySlug: 'solano-county', pop: 119533, lat: 38.2494, lng: -122.0400, courthouse: 'Solano Superior Court', recorder: 'Solano County Clerk-Recorder' },
  { city: 'Vista', slug: 'vista', county: 'San Diego', countySlug: 'san-diego-county', pop: 101838, lat: 33.2000, lng: -117.2425, courthouse: 'North County Regional Center', recorder: 'San Diego County Assessor/Recorder' },
  { city: 'Ventura', slug: 'ventura', county: 'Ventura', countySlug: 'ventura-county', pop: 110763, lat: 34.2805, lng: -119.2945, courthouse: 'Ventura Superior Court', recorder: 'Ventura County Clerk-Recorder' },
  { city: 'Petaluma', slug: 'petaluma', county: 'Sonoma', countySlug: 'sonoma-county', pop: 61328, lat: 38.2324, lng: -122.6367, courthouse: 'Sonoma Superior Court', recorder: 'Sonoma County Clerk-Recorder-Assessor' },
  { city: 'Vacaville', slug: 'vacaville', county: 'Solano', countySlug: 'solano-county', pop: 102386, lat: 38.3565, lng: -121.9877, courthouse: 'Solano Superior Court', recorder: 'Solano County Clerk-Recorder' },
  { city: 'Hesperia', slug: 'hesperia', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 102521, lat: 34.4263, lng: -117.3009, courthouse: 'Victorville Courthouse', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Calexico', slug: 'calexico', county: 'Imperial', countySlug: 'imperial-county', pop: 40398, lat: 32.6789, lng: -115.4989, courthouse: 'Imperial Superior Court', recorder: 'Imperial County Clerk-Recorder' },
  { city: 'Yucaipa', slug: 'yucaipa', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 55038, lat: 34.0336, lng: -117.0431, courthouse: 'San Bernardino Justice Center', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Hemet', slug: 'hemet', county: 'Riverside', countySlug: 'riverside-county', pop: 91097, lat: 33.7475, lng: -116.9720, courthouse: 'Hemet Courthouse', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Lake Forest', slug: 'lake-forest', county: 'Orange', countySlug: 'orange-county', pop: 87360, lat: 33.6469, lng: -117.6892, courthouse: 'Lamoreaux Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'Norwalk', slug: 'norwalk-ca', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 103949, lat: 33.9022, lng: -118.0817, courthouse: 'Norwalk Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Hawthorne', slug: 'hawthorne', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 88083, lat: 33.9164, lng: -118.3526, courthouse: 'Torrance Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Citrus Heights', slug: 'citrus-heights', county: 'Sacramento', countySlug: 'sacramento-county', pop: 87945, lat: 38.7073, lng: -121.2810, courthouse: 'Sacramento Superior Court', recorder: 'Sacramento County Clerk-Recorder' },
  { city: 'Alhambra', slug: 'alhambra', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 83089, lat: 34.0953, lng: -118.1270, courthouse: 'Alhambra Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Tracy', slug: 'tracy', county: 'San Joaquin', countySlug: 'san-joaquin-county', pop: 92895, lat: 37.7397, lng: -121.4252, courthouse: 'San Joaquin Superior Court', recorder: 'San Joaquin County Clerk-Recorder' },
  { city: 'Chico', slug: 'chico', county: 'Butte', countySlug: 'butte-county', pop: 103079, lat: 39.7285, lng: -121.8375, courthouse: 'Butte Superior Court', recorder: 'Butte County Clerk-Recorder' },
  { city: 'San Mateo', slug: 'san-mateo', county: 'San Mateo', countySlug: 'san-mateo-county', pop: 105661, lat: 37.5630, lng: -122.3255, courthouse: 'Hall of Justice & Records', recorder: 'San Mateo County Clerk-Recorder' },
  { city: 'Menifee', slug: 'menifee', county: 'Riverside', countySlug: 'riverside-county', pop: 102527, lat: 33.6971, lng: -117.1850, courthouse: 'Southwest Justice Center', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'South Gate', slug: 'south-gate', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 94396, lat: 33.9547, lng: -118.2120, courthouse: 'Compton Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Whittier', slug: 'whittier', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 87713, lat: 33.9792, lng: -118.0326, courthouse: 'Whittier Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Jurupa Valley', slug: 'jurupa-valley-ca', county: 'Riverside', countySlug: 'riverside-county', pop: 106993, lat: 33.9975, lng: -117.4855, courthouse: 'Riverside Superior Court', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Newport Beach', slug: 'newport-beach', county: 'Orange', countySlug: 'orange-county', pop: 85239, lat: 33.6189, lng: -117.9289, courthouse: 'Harbor Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'San Leandro', slug: 'san-leandro', county: 'Alameda', countySlug: 'alameda-county', pop: 90834, lat: 37.7249, lng: -122.1561, courthouse: 'Wiley W. Manuel Courthouse', recorder: 'Alameda County Clerk-Recorder' },
  { city: 'Indio', slug: 'indio', county: 'Riverside', countySlug: 'riverside-county', pop: 89137, lat: 33.7206, lng: -116.2156, courthouse: 'Larson Justice Center', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Lakewood', slug: 'lakewood', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 80048, lat: 33.8536, lng: -118.1337, courthouse: 'Long Beach Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Napa', slug: 'napa', county: 'Napa', countySlug: 'napa-county', pop: 79652, lat: 38.2975, lng: -122.2869, courthouse: 'Napa Superior Court', recorder: 'Napa County Clerk-Recorder' },
  { city: 'Tulare', slug: 'tulare', county: 'Tulare', countySlug: 'tulare-county', pop: 68073, lat: 36.2077, lng: -119.3473, courthouse: 'Tulare Superior Court', recorder: 'Tulare County Clerk-Recorder' },
  { city: 'Palm Springs', slug: 'palm-springs', county: 'Riverside', countySlug: 'riverside-county', pop: 44575, lat: 33.8303, lng: -116.5453, courthouse: 'Larson Justice Center', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Redding', slug: 'redding', county: 'Shasta', countySlug: 'shasta-county', pop: 92651, lat: 40.5865, lng: -122.3917, courthouse: 'Shasta Superior Court', recorder: 'Shasta County Clerk-Recorder' },
  { city: 'Turlock', slug: 'turlock', county: 'Stanislaus', countySlug: 'stanislaus-county', pop: 74958, lat: 37.4947, lng: -120.8466, courthouse: 'Stanislaus Superior Court', recorder: 'Stanislaus County Clerk-Recorder' },
  { city: 'Merced', slug: 'merced', county: 'Merced', countySlug: 'merced-county', pop: 84654, lat: 37.3022, lng: -120.4830, courthouse: 'Merced Superior Court', recorder: 'Merced County Clerk-Recorder' },
  { city: 'Madera', slug: 'madera', county: 'Madera', countySlug: 'madera-county', pop: 66256, lat: 36.9613, lng: -120.0607, courthouse: 'Madera Superior Court', recorder: 'Madera County Clerk-Recorder' },
  { city: 'Redlands', slug: 'redlands', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 73522, lat: 34.0556, lng: -117.1825, courthouse: 'San Bernardino Justice Center', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Compton', slug: 'compton-ca', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 97559, lat: 33.8958, lng: -118.2201, courthouse: 'Compton Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Colton', slug: 'colton', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 55686, lat: 34.0739, lng: -117.3134, courthouse: 'San Bernardino Justice Center', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Perris', slug: 'perris', county: 'Riverside', countySlug: 'riverside-county', pop: 78608, lat: 33.7825, lng: -117.2286, courthouse: 'Southwest Justice Center', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Beaumont', slug: 'beaumont', county: 'Riverside', countySlug: 'riverside-county', pop: 53558, lat: 33.9294, lng: -116.9772, courthouse: 'Banning Courthouse', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Manteca', slug: 'manteca', county: 'San Joaquin', countySlug: 'san-joaquin-county', pop: 85285, lat: 37.7974, lng: -121.2163, courthouse: 'San Joaquin Superior Court', recorder: 'San Joaquin County Clerk-Recorder' },
  { city: 'Rialto', slug: 'rialto-ca', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 103526, lat: 34.1064, lng: -117.3703, courthouse: 'San Bernardino Justice Center', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Inglewood', slug: 'inglewood-ca', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 109673, lat: 33.9617, lng: -118.3531, courthouse: 'Inglewood Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'San Marcos', slug: 'san-marcos', county: 'San Diego', countySlug: 'san-diego-county', pop: 97698, lat: 33.1434, lng: -117.1661, courthouse: 'North County Regional Center', recorder: 'San Diego County Assessor/Recorder' },
  { city: 'Murrieta', slug: 'murrieta-ca', county: 'Riverside', countySlug: 'riverside-county', pop: 116800, lat: 33.5539, lng: -117.2139, courthouse: 'Southwest Justice Center', recorder: 'Riverside County Assessor-Clerk-Recorder' },
  { city: 'Hawthorne', slug: 'hawthorne-ca', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 88083, lat: 33.9164, lng: -118.3526, courthouse: 'Torrance Courthouse', recorder: 'LA County Registrar-Recorder' },
  // Adding more cities to approach 482...
  { city: 'Lodi', slug: 'lodi', county: 'San Joaquin', countySlug: 'san-joaquin-county', pop: 68012, lat: 38.1302, lng: -121.2724, courthouse: 'San Joaquin Superior Court', recorder: 'San Joaquin County Clerk-Recorder' },
  { city: 'Pittsburg', slug: 'pittsburg', county: 'Contra Costa', countySlug: 'contra-costa-county', pop: 75432, lat: 38.0280, lng: -121.8847, courthouse: 'Pittsburg Courthouse', recorder: 'Contra Costa County Clerk-Recorder' },
  { city: 'Livermore', slug: 'livermore', county: 'Alameda', countySlug: 'alameda-county', pop: 95074, lat: 37.6819, lng: -121.7681, courthouse: 'East County Hall of Justice', recorder: 'Alameda County Clerk-Recorder' },
  { city: 'Pleasanton', slug: 'pleasanton', county: 'Alameda', countySlug: 'alameda-county', pop: 82618, lat: 37.6624, lng: -121.8747, courthouse: 'East County Hall of Justice', recorder: 'Alameda County Clerk-Recorder' },
  { city: 'Santa Cruz', slug: 'santa-cruz', county: 'Santa Cruz', countySlug: 'santa-cruz-county', pop: 65178, lat: 36.9741, lng: -122.0308, courthouse: 'Santa Cruz Superior Court', recorder: 'Santa Cruz County Clerk-Recorder' },
  { city: 'Mission Viejo', slug: 'mission-viejo', county: 'Orange', countySlug: 'orange-county', pop: 94381, lat: 33.6000, lng: -117.6719, courthouse: 'Lamoreaux Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'Tustin', slug: 'tustin', county: 'Orange', countySlug: 'orange-county', pop: 80346, lat: 33.7458, lng: -117.8261, courthouse: 'Central Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'Westminster', slug: 'westminster', county: 'Orange', countySlug: 'orange-county', pop: 90911, lat: 33.7514, lng: -117.9940, courthouse: 'West Justice Center', recorder: 'OC Clerk-Recorder' },
  { city: 'Milpitas', slug: 'milpitas', county: 'Santa Clara', countySlug: 'santa-clara-county', pop: 80273, lat: 37.4323, lng: -121.8996, courthouse: 'Santa Clara Superior Court', recorder: 'Santa Clara County Clerk-Recorder' },
  { city: 'Covina', slug: 'covina', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 48956, lat: 34.0900, lng: -117.8903, courthouse: 'West Covina Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Upland', slug: 'upland', county: 'San Bernardino', countySlug: 'san-bernardino-county', pop: 79040, lat: 34.0975, lng: -117.6484, courthouse: 'Rancho Cucamonga Courthouse', recorder: 'SB County Assessor-Recorder-Clerk' },
  { city: 'Pico Rivera', slug: 'pico-rivera', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 62942, lat: 33.9831, lng: -118.0967, courthouse: 'Whittier Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Carlsbad', slug: 'carlsbad', county: 'San Diego', countySlug: 'san-diego-county', pop: 115382, lat: 33.1581, lng: -117.3506, courthouse: 'North County Regional Center', recorder: 'San Diego County Assessor/Recorder' },
  { city: 'San Buenaventura', slug: 'san-buenaventura', county: 'Ventura', countySlug: 'ventura-county', pop: 110763, lat: 34.2805, lng: -119.2945, courthouse: 'Ventura Superior Court', recorder: 'Ventura County Clerk-Recorder' },
  { city: 'Norwalk', slug: 'norwalk-los-angeles', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 103949, lat: 33.9022, lng: -118.0817, courthouse: 'Norwalk Courthouse', recorder: 'LA County Registrar-Recorder' },
  { city: 'Oxnard', slug: 'oxnard-ca', county: 'Ventura', countySlug: 'ventura-county', pop: 202063, lat: 34.1975, lng: -119.1771, courthouse: 'Ventura Superior Court', recorder: 'Ventura County Clerk-Recorder' },
  { city: 'Norwalk', slug: 'norwalk-la-county', county: 'Los Angeles', countySlug: 'los-angeles-county', pop: 103949, lat: 33.9022, lng: -118.0817, courthouse: 'Norwalk Courthouse', recorder: 'LA County Registrar-Recorder' },
];

// For the generator script — deduplicate and use unique slugs
export const CITIES = CA_CITIES.filter((c, i, arr) => arr.findIndex(x => x.slug === c.slug) === i);

export const CA_COUNTIES = [
  { name: 'Los Angeles County', slug: 'los-angeles-county', cities: 88 },
  { name: 'San Diego County', slug: 'san-diego-county', cities: 18 },
  { name: 'Orange County', slug: 'orange-county', cities: 34 },
  { name: 'Riverside County', slug: 'riverside-county', cities: 28 },
  { name: 'San Bernardino County', slug: 'san-bernardino-county', cities: 24 },
  { name: 'Santa Clara County', slug: 'santa-clara-county', cities: 15 },
  { name: 'Alameda County', slug: 'alameda-county', cities: 14 },
  { name: 'Sacramento County', slug: 'sacramento-county', cities: 8 },
  { name: 'Contra Costa County', slug: 'contra-costa-county', cities: 19 },
  { name: 'Fresno County', slug: 'fresno-county', cities: 15 },
  { name: 'Kern County', slug: 'kern-county', cities: 8 },
  { name: 'San Joaquin County', slug: 'san-joaquin-county', cities: 9 },
  { name: 'Ventura County', slug: 'ventura-county', cities: 10 },
  { name: 'San Mateo County', slug: 'san-mateo-county', cities: 20 },
  { name: 'Stanislaus County', slug: 'stanislaus-county', cities: 9 },
  { name: 'Solano County', slug: 'solano-county', cities: 7 },
  { name: 'Tulare County', slug: 'tulare-county', cities: 9 },
  { name: 'Sonoma County', slug: 'sonoma-county', cities: 9 },
  { name: 'Marin County', slug: 'marin-county', cities: 11 },
  { name: 'Santa Barbara County', slug: 'santa-barbara-county', cities: 8 },
];
